name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.0.0
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze project source
        run: flutter analyze
        
      - name: Run Flutter tests
        run: flutter test
        
      - name: Run Dart tests
        run: dart test
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Build iOS
        run: flutter build ios --release --no-codesign
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          
      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: release-ios
          path: build/ios/ipa
          retention-days: 7
          
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build/
            .dart_tool/
            .flutter-plugins
            .flutter-plugins-dependencies
          retention-days: 7 
